### ISSUE TITLE
Compilator should generate documentation for the non hidden variables of the function block into the documentation of the PLC block.

### ISSUE THREAD

**Issue by TomKovac** [Inxton/Feedback#1]
Compilator should generate documentation for the non hidden variables of the function block into the documentation of the PLC block.

**Comment by Inxton-Dev** [comment]
#GHIF#1 #1 
@TomKovac  you can grab v1.9.4-alpha.186(+) from internal feed or wait for nightly tomorrow morning. We will publish on NuGet.org next week. Enjoy! Expecting feedback.

**Comment by TomKovac** [comment]
Thanks @Inxton-Dev  seems to work, will keep in touch
