### ISSUE TITLE
Bug or Error?

### ISSUE THREAD

**Issue by kumaraswamygaviyappa** [Inxton/Feedback#10]
TwinCAT3.1 is Building but  Inxton Build FAILS for below code:
**`DO_DurchflSetCounter at %Q*: BOOL;`
`Zustand: ARRAY[0..maxAnzahlMeldungen50-1] OF ST_Meldungen_EC;`**

and Build PASS for small change in the code:
**`DO_DurchflSetCounter AT %Q*: BOOL;`
`Zustand: ARRAY[0..49] OF ST_Meldungen_EC;`**

Error:
![image](https://user-images.githubusercontent.com/10028131/115376426-fcb53100-a1ce-11eb-8eb3-1a78f8032d32.png)

**Comment by jozefchmelar** [comment]
Hi @kumaraswamygaviyappa 

For now Inxton doesn't support expressions in array size initialization. You can use either a constant variable or a constant number

https://docs.inxton.com/docu/articles/units/Inxton.vortex.compiler.console/README.html#arrays

**Comment by jozefchmelar** [comment]
Closing.
