### ISSUE TITLE
Visual Studio crash on inxton build if project contains a TwinCAT Drive Manager 2 project

### ISSUE THREAD

**Issue by rruiter87** [Inxton/Feedback#11]
**Describe the bug**
I'm trying to build a plc project using Inxton. Since adding a drive manager project, visual studio crashes. I see the following when I start the build.

```
Inxton compiler cli version : 1.15.9.0 / 1.15.9-alpha.703+Branch.develop.Sha.9651e8bebbead861cdb3ff7acea06cdc532603e5
2022-06-28 09:45:12 INF Builder version : 1.15.9.0 / 1.15.9-alpha.703+Branch.develop.Sha.9651e8bebbead861cdb3ff7acea06cdc532603e5
2022-06-28 09:45:12 INF Opening solution: C:\path\to\solution.sln
2022-06-28 09:45:12 INF Language mutation of VS 'en'
2022-06-28 09:45:12 INF Loading dependency tree for project 'C:\path\to\PlcConnector\PlcConnector.csproj'
```

Then after a few seconds Visual Studio crashes.

**To Reproduce**
1. Create a new TwinCAT XAE project with a PLC project
2. Add a PlcConnector project to the solution
3. Add a [TwinCAT Drive Manager 2 Project](https://www.beckhoff.com/en-en/products/automation/twincat/te1xxx-twincat-3-engineering/te5950.html)
4. Build with inxton
5. Crash!

**Desktop (please complete the following information):**
 - Microsoft Visual Studio Community 2019 Version 16.11.13

**Workaround**
Unload the TwinCAT Drive manager project to build the project.

**Comment by Inxton-Dev** [comment]
Thanks for reporting @rruiter87.
We are trying to reproduce without much success, would you it be possible to provide a sample project?

Could you run inxton builder from PowerShell:

~~~
cd your_solution_folder
.\_Vortex\builder\vortex.compiler.console.exe -s .\your_solution.sln -n false
~~~

what is the result?

**Comment by rruiter87** [comment]
```
 ❯ .\_Vortex\builder\vortex.compiler.console.exe -s .\solution.sln
Inxton compiler cli version : 1.15.7.0 / 1.15.7-alpha.695+Branch.develop.Sha.445dcc7ea2f8283f45f7a1fb88d3a005d104ea09
2022-06-28 13:03:59 INF Builder version : 1.15.7.0 / 1.15.7-alpha.695+Branch.develop.Sha.445dcc7ea2f8283f45f7a1fb88d3a005d104ea09
2022-06-28 13:03:59 WRN >>>>>>"W","","Config file C:\path\to\vortex_config.json does not exists. Creating default one with defaults.","","","0","0"
2022-06-28 13:04:01 INF Opening solution: .\solution.sln
2022-06-28 13:04:03 INF Language mutation of VS 'en'
2022-06-28 13:04:04 INF Loading dependency tree for project 'C:\path\to\PlcConnector\PlcConnector.csproj'
2022-06-28 13:04:10 ERR >>>>>>"E","","Failed to retrieve Tc project 'Plc'
'Unable to attach to any Tc project (TcSysManager).'","","","0","0"
```

Example project which crashes on Inxton build if the `Test` drive manager project is enabled. When you unload the drive manager project, the Inxton builder works again.
[InxtonCrash.zip](https://github.com/Inxton/Feedback/files/9000444/InxtonCrash.zip)

**Comment by Inxton-Dev** [comment]
@rruiter87 as a quick fix you can modify your PlcConnector.csproj file like this:

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/60608129/176229080-a0239366-a46e-415f-b11e-e5329f7b89b2.png">

You will need to build the project first within the VS it will copy new version of the compiler into your project, then you should be able to run the ivf with the drive project loaded in your solution.

`PlcConnector.csproj`
~~~XML
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
	<PackageReference Include="Inxton.vortex.compiler.console" Version="1.15.9-alpha.719" />
    <PackageReference Include="TcOpen.Group" Version="0.5.0-alpha.834" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Localizations.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Localizations.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Localizations.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Localizations.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
~~~

TcOpen should release new packages tonight with the update of inxton libraries, where this issue is fixed.

Let us know how this plays out for you...

**Comment by rruiter87** [comment]
Thanks for the quick response and fix. I just updated to the latest version and can confirm it is now fixed.
