### ISSUE TITLE
Twin assembly version and twincat project version reports as mismatched, even though they are configured to be the same

### ISSUE THREAD

**Issue by JonasJurczok** [Inxton/Feedback#16]
Hello,

I stumbled upon the next issue.

During builds I get the warning "WRN Twin assembly version (0.0.0.0) and plc project version (0.1.0) do not match. You need to adjust the version of the plc project manually. Project property tab version."

Under twincat project -> properties -> version I configured the version to be 0.1.0.
How do I set the corresponding version in the connector project?

I tried setting it in the project properties and in the .csproj file. Both seem to have no effect.

````
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyVersion>0.1.0</AssemblyVersion>
    <Version>0.1.0</Version>
  </PropertyGroup>
...
</Project>
````

What is the correct way to configure the c# project version that is recognized by the inxton compiler?

**Comment by PTKu** [comment]
Hi @JonasJurczok 

you will need to modify the `AssemblyInfo.cs` file that is located in Property directory of your project. If it does not exist you will need to create one. The compiler is looking for the version number there. You will also need to have the property `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>` set to `false` as you have in the snippet above.

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/61538034/199553169-11980067-6823-4fad-92d6-d12d435cf6ca.png">

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/61538034/199553523-3dc6b4a0-7031-454e-a86c-1a6bce068f7c.png">

It should look something like this:

```C#
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyVersion("0.6.0.0")]
[assembly: AssemblyFileVersion("0.6.0.0")]
[assembly: AssemblyInformationalVersion("0.6.0-master.913+Branch.master.Sha.4c84548ce65902faf186e6b2f45c239f599f2d02")]
```
Compiler goes after `AssemblyInformationalVersion` version attribute.

So in you case you set like this:
```C#
[assembly: AssemblyInformationalVersion("0.1.0-branch.0+Branch.branch.Sha.cccccccccccccccccccccccccccccccccccccccc")]
```
let me know if that works

**Comment by JonasJurczok** [comment]
Thanks for the quick response.
This solved the problem. Thanks. I'll read up on the differences.

It's very confusing that there are multiple different ways to set a version :)
