### ISSUE TITLE
Reading/Writing variables blocks and does nt return a value&set the value in the PLC

### ISSUE THREAD

**Issue by JonasJurczok** [Inxton/Feedback#18]
Hello :)

We are currently trying out Inxton on our physical testbed. Suddenly reading/writing values des not work anymore.
The code is identical to the examples provided in your documentaton and our previous tests.
The only difference we can find is that our AMS ID is now a remote one and not null (for localhost).

Are there caveats for remote ADS connections?
We can log into the machine just fine with Visual Studio and every other tool is working normally as expected.

Is there a way to debug Inxton and discover underlying issues?

Best,
Jonas

**Comment by PTKu** [comment]
This is a strange. There is no difference between `local` and `remote`, except for the transport layer.  

When you construct the connector you can pass in the third parameter `true`. It will open the console window at startup where will appear diagnostic messages from the connector if any.

e.g.
```
public static PlcHammer.PlcHammerTwinController PlcHammer { get; }
            = new PlcHammer.PlcHammerTwinController(Tc3ConnectorAdapter.Create(AmsId, 851, true));
```

Let me know if you can spot something there.

**Comment by JonasJurczok** [comment]
HEy,
thanks for the quick reply.

Changing the value makes no difference in console output.
However this is what we get.

````
[16:54:10 INF] Creating objects...
[16:54:10 INF] Total count of targets tags is 0
[16:54:10 INF] Creating objects... Done
[16:54:10 INF] Connecting to controller AMS ((our ams ID)) port 851
Initializing connector... start
---------------------------------------------------------------
[16:54:10 INF] Symbol loading mode: LoadAndLinkOnTheFly
[16:54:10 INF] Start rw ops...
[16:54:10 INF] Start rw ops... Done
Initializing connector... done
---------------------------------------------------------------
[16:54:10 INF] Reading identities...
[16:54:10 INF] Reading identities done.
[16:54:10 INF] Number of identities: 0 | Unique :0
[16:54:10 INF] Sorting identities...
[16:54:10 INF] Sorting identities done.
````

From my perspective it looks identitcal to our working examples.

**Comment by JonasJurczok** [comment]
I just saw we actually get Inxton errors in the debug terminal.

````
Ads Warning: 1 : [AdsSymbolParser:ParseTypes()] Cannot parse DataTypeEntry. Skipping dataType
Ads Warning: 1 : [AdsSymbolParser:ParseTypes()] Exception: Specified method is not supported.
Ads Warning: 1 : [AdsSymbolParser:ParseTypes()] Cannot parse DataTypeEntry. Skipping dataType
Ads Warning: 1 : [AdsSymbolParser:ParseTypes()] Exception: Specified method is not supported.
Ads Warning: 1 : [AdsSymbolParser:ParseTypes()] Cannot parse DataTypeEntry. Skipping dataType
Ads Warning: 1 : [AdsSymbolParser:ParseTypes()] Exception: Specified method is not supported.
````

Is there a way to check what the problem was? Because we access a variable of type int, exactly like in our previous tests.

**Comment by PTKu** [comment]
Hmm... when you say it suddenly stops R/W how do you observe it in the PLC watch tables or in some other application? If there were any exception they would appear in the console. One question though which .net framework do you use? 

Those warnings are weird... can you have a look if you're referencing Ads nuget package or dll in your project in addition to Inxton.Vortex.Connectors?

**Comment by PTKu** [comment]
One more question, are you using `TcRpc` methods?

**Comment by JonasJurczok** [comment]
It stops by literally blocking. `main.counter.Synchron` just never returns.
When writing there is no change in the online watch tables. No other exceptions anywhere than what I posted here.

We use .net 5.0.

````
<ItemGroup>
    <PackageReference Include="Inxton.Package.Vortex.Core" Version="1.15.4" />
    <PackageReference Include="Inxton.vortex.compiler.console" Version="1.15.4" />
  </ItemGroup>
````
No other references.
These two have been there for all our tests, though.

**Comment by PTKu** [comment]
.net5 is experimental, net4.8 is supported

anyways can you try to reference 1.15.11-alpha.749

<ItemGroup>
    <PackageReference Include="Inxton.Package.Vortex.Core" Version="1.15.11-alpha.749" />
    <PackageReference Include="Inxton.vortex.compiler.console" Version="1.15.11-alpha.749" />
</ItemGroup>

that version passed all tests and was staged for quite a time in production. There were some fixies I am not sure which version now... try 1.15.11-alpha.749 and let me know...

**Comment by JonasJurczok** [comment]
To clarify:

C# console code:
````
static void Main(string[] args)
        {
            PLCConnector.Entry.plc.Connector.BuildAndStart();
            var main = PLCConnector.Entry.plc.MAIN;

            while (true)
            {
                Console.WriteLine($"Counter is {main.counter.Synchron}");
                Console.ReadKey();
            }
            Console.WriteLine("Press any key to exit.");
            Console.ReadKey();
        }
````

There is a corresponding PLC Main with a counter variable.

When I deploy this PLC app localy and connect with the console to it, it works.

When I change the AMS Net ID to our physical PLC in the test cell then it stops working as described above.

**Comment by JonasJurczok** [comment]
````
Inxton compiler cli version : 1.15.11.0 / 1.15.11-alpha.749+Branch.develop.Sha.ab3e1dd23f1b7ff06ebdf8378636d90d0f290e40
2022-11-15 17:18:34 INF Builder version : 1.15.11.0 / 1.15.11-alpha.749+Branch.develop.Sha.ab3e1dd23f1b7ff06ebdf8378636d90d0f290e40
2022-11-15 17:18:34 INF Opening solution: XXXThursdayDemo.sln
2022-11-15 17:18:34 INF Language mutation of VS 'en'
2022-11-15 17:18:34 WRN Project 'PLC' has no namespace defined. Namespace defaults to project name.
2022-11-15 17:18:34 INF Loading dependency tree for project 'XXXThursdayDemo\PLCConnector\PLCConnector.csproj'
2022-11-15 17:18:34 INF Tc system manager 'XXXThursdayDemo\ThursdayDemo\ThursdayDemo.tsproj' retrieved.
````

No change in behaviour :(

**Comment by PTKu** [comment]
> ```
> static void Main(string[] args)
>         {
>             PLCConnector.Entry.plc.Connector.BuildAndStart();
>             var main = PLCConnector.Entry.plc.MAIN;
> 
>             while (true)
>             {
>                 Console.WriteLine($"Counter is {main.counter.Synchron}");
>                 Console.ReadKey();
>             }
>             Console.WriteLine("Press any key to exit.");
>             Console.ReadKey();
>         }
> ```

This piece of code gets stuck?



> ```
> Inxton compiler cli version : 1.15.11.0 / 1.15.11-alpha.749+Branch.develop.Sha.ab3e1dd23f1b7ff06ebdf8378636d90d0f290e40
> 2022-11-15 17:18:34 INF Builder version : 1.15.11.0 / 1.15.11-alpha.749+Branch.develop.Sha.ab3e1dd23f1b7ff06ebdf8378636d90d0f290e40
> 2022-11-15 17:18:34 INF Opening solution: XXXThursdayDemo.sln
> 2022-11-15 17:18:34 INF Language mutation of VS 'en'
> 2022-11-15 17:18:34 WRN Project 'PLC' has no namespace defined. Namespace defaults to project name.
> 2022-11-15 17:18:34 INF Loading dependency tree for project 'XXXThursdayDemo\PLCConnector\PLCConnector.csproj'
> 2022-11-15 17:18:34 INF Tc system manager 'XXXThursdayDemo\ThursdayDemo\ThursdayDemo.tsproj' retrieved.
> ```
> 
> No change in behaviour :(

There must be something with the network... any routers in between?

**Comment by JonasJurczok** [comment]
Yeah, I switched to .net4.8 and it works now.

That is super weird, but I'll take it. We can continue our test. Thank you for the support and have a great evening :)
