### ISSUE TITLE
Examples activation problem

### ISSUE THREAD

**Issue by pierk007** [Inxton/Feedback#3]
Hello

I'm activating Vortex.Core.Examples TwinCAT project but I'm getting following error
```

TwinCAT System' (10000): Sending ams command >> Init4\RTime: Start Interrupt: Ticker started >> AdsError: 4120 (0x1018, RTIME: enter real-time mode fails: Intel VT-x extension not enabled (in Bios)!) << failed!        

```
Help me?

**Comment by jozefchmelar** [comment]
Hello @pierk007 

I recommend to run the TwinCAT application on an isolated core to avoid this error.

Here's how to do it 

Go to
![image](https://user-images.githubusercontent.com/11136013/109816677-494da880-7c31-11eb-843b-babc9e8443d6.png)

Click on "Read from target"
![image](https://user-images.githubusercontent.com/11136013/109816701-5074b680-7c31-11eb-80bc-c409726581a6.png)

You should get a list of all your CPU cores...Listed from 0 to X

Click on "Set on Target" and you should get this box

![image](https://user-images.githubusercontent.com/11136013/109816818-75692980-7c31-11eb-9e39-b390f10ece55.png)
Your numbers will be a bit different but it's important to have the "1" in the rightmost box. 
If you have 12 CPU cores as I have, I'm keeping 11 cores for myself and 1 for TwinCAT

After you click on SET you have to select the RT-Core to run on the Isolated Core.
You have to restart your computer.

After that, run the RT-Core on Isolated CPU Core.

![image](https://user-images.githubusercontent.com/11136013/109817054-be20e280-7c31-11eb-928c-d23ff816da17.png)

**Comment by pierk007** [comment]
Thanks!!! @jozefchmelar. I also found out the right setting in BIOS enabling VT-x... I guess I will try this solution as well

**Comment by jozefchmelar** [comment]
Glad it works. I'm closing the issue.
