### ISSUE TITLE
WPF application preformance issue while running with debugger

### ISSUE THREAD

**Issue by JurajSpisiak** [Inxton/Feedback#4]
Running wpf application using package Inxton.Vortex.Presentation.Styling with debugger causes performance issues.

**Comment by Inxton-Dev** [comment]
In some instances there are exceptions thrown during debugging that originate in libraries that are out of reach for us. 
Check please that you have item: 

```Tools -> Options -> Debugging -> General -> Enable Just My Code``` set to ```true```

![EnableJustMyCode](https://user-images.githubusercontent.com/60608129/110091513-ce9f9d00-7d98-11eb-8851-c1e9749e55ed.png)
