### ISSUE TITLE
Missing namespace

### ISSUE THREAD

**Issue by peterbarancek** [Inxton/Feedback#5]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/62284244/110642383-43b50d00-81b3-11eb-8736-4e4454e9c140.png)

Hi, when I add a new twincat project and run the builder, generated files are missing a namespace.  How to add the namespace?

**Comment by PTKu** [comment]
@jozefchmelar we should warn at compile time about missing namespace || or use project name as namespace instead

**Comment by jozefchmelar** [comment]
@PTKu let's use the project name as the default namespace.

**Comment by PTKu** [comment]
OK FOXTROTH#455

**Comment by PTKu** [comment]
Fixed in FXT PR943
internal v1.9.6-alpha.258
external-pre-release *not-released yet*
external release *not-released yet*
