### ISSUE TITLE
class library disappears -100_InxtonCoreConsole

### ISSUE THREAD

**Issue by kumaraswamygaviyappa** [Inxton/Feedback#7]
Hello,

I could follow each steps available in "100 InxtonCoreConsole Tutorial" in youtube.
Problem occurs when i click "Intox-Vortes Build". The class library disappears.

Created Project:
![image](https://user-images.githubusercontent.com/10028131/111606113-2c8ba600-87d7-11eb-8534-12b054082fda.png)

Before the Build:
![image](https://user-images.githubusercontent.com/10028131/111606312-5e047180-87d7-11eb-9668-deff1d6a2599.png)

After the Build:
![image](https://user-images.githubusercontent.com/10028131/111606730-de2ad700-87d7-11eb-9c5c-0c5f65f0db39.png)

RoomControllerConnector - Class library disappears:
![image](https://user-images.githubusercontent.com/10028131/111606679-cbb09d80-87d7-11eb-9ea0-5f21b0db516c.png)

Errors:
![image](https://user-images.githubusercontent.com/10028131/111606492-8f7d3d00-87d7-11eb-95fc-5b469c49fd04.png)

![image](https://user-images.githubusercontent.com/10028131/111606565-a4f26700-87d7-11eb-8f40-2a6830651edb.png)

**Comment by jozefchmelar** [comment]
Hi @kumaraswamygaviyappa 

Thank you for submitting this very thorough issue.

 The problem is that new versions of Inxton builder is expecting the new csproj format, but the tutorial example uses the old format.
 
new csproj format - https://github.com/Inxton/Examples-Inxton.Package.Vortex.Core/blob/master/HansPlcConnector/HansPlcConnector.csproj

old csproj format - https://github.com/Inxton/Tutorials-Inxton.Package.Vortex.Core/blob/master/101_InxtonCoreConsoleReadFromPLC/RoomControllerConnector/RoomControllerConnector.csproj

To solve it you could either downgrade Inxton to previous version, or replace the csproj with the new format.


Anyway, we'll update the tutorials so they work with the latest csproj format.

Thank you, and sorry for the inconvenience. I

**Comment by Inxton-Dev** [comment]
@kumaraswamygaviyappa 
we moved to new format from version:
https://github.com/Inxton/Inxton.Package.Vortex.Core/releases/tag/v1.9.3
the examples should work with version:
https://github.com/Inxton/Inxton.Package.Vortex.Core/releases/tag/v1.6.5 and earlier

Thank you for reporting the issue we will update the examples; when updated we will report here.

**Comment by kumaraswamygaviyappa** [comment]
Hello @jozefchmelar @Inxton-Dev ,

Thank you for the response. 
The example (100 InxtonCoreConsole Tutorial) in the GitHub is working fine but i need to create new project for my requirements. Is there any way i can do it?

Also i couldn't find "Inxton - Vortex Builder extension v1.6.5"

**Comment by Inxton-Dev** [comment]
Good morning @kumaraswamygaviyappa

Any TwinCAT Plc project can have its ```twin``` counterpart. You only need to add C# library project to the same solution that has name [PlcProjectName]+Connector. So if your PLC project is ```MyPlc``` your twin connector will be ```MyPlcConnector```.

General info here: https://docs.inxton.com/docu/articles/units/Inxton.vortex.compiler.console/README.html

how to connect to connector project here https://docs.inxton.com/docu/articles/units/Inxton.vortex.compiler.console/README.html#how-to-access-twincontroller

You should use latest Vortex Builder extension v 1.0.5.0. It is fine with all versions of Inxton Vortex compiler. The compiler is packed in nuget package and it is installed as tool when referenced in your project.

If you are to create new project I would advise you to go with newest versions.

https://www.nuget.org/packages/Inxton.Package.Vortex.Core/1.9.4

**Be aware that works with the new format of ```csproj```.  We will update the tutorial repo as asap.**

[teaminternalinforeference]Tutorials schedule to be solved in FXT#500 Fix tutorials repo to new file format in connectors.

**Comment by kumaraswamygaviyappa** [comment]
Hello @Inxton-Dev,

I would run my own project using `Install-Package Inxton.Package.Vortex.Core -Version 1.6.5`
But still facing problem with v1.9.3. will wait for updated tutorial.
correct me if wrong, I need to `Build Inxtron Vortex` every time if there is a change in PLC or C# project. Right?

Looking forward to learn much on Inxton. 
My usecase is for MIL, SIL. Let me discover how can i achieve using Inxton. 
Could you please point me if there are any application notes by Inxton.

[This one](https://alltwincat.com/2021/02/16/unit-testing-in-the-world-of-industrial-automation/) brought me here.

**Comment by jozefchmelar** [comment]
Hi @kumaraswamygaviyappa  

Try to build the `[NameOfPlcProject]Connector` project first - it should copy the vortex builder in the correct folder. Then run the builder.

You need to run the builder everytime there's a change in the PLC project strucutre (like adding a new variable or function block)

**Comment by PTKu** [comment]
> If it's not working, add the ` <PackageReference Include="Inxton.Vortex.Compiler.Console" Version="1.9.6" />` to the csproj file and build the connector project again . 
@jozefchmelar This will work only in new format  and v1.9.6 is not yet released on nuget.org latest version is 1.9.4

csproj file should look something like:

~~~ XML
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
     <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Inxton.Package.Vortex.Core" Version="1.9.4" />
  </ItemGroup>
</Project>
~~~

**Comment by jozefchmelar** [comment]
There's  PR pending https://github.com/Inxton/Tutorials-Inxton.Package.Vortex.Core/pull/2

@kumaraswamygaviyappa  were you able to get the project up and running?

**Comment by kumaraswamygaviyappa** [comment]
Hello,

 `-Version 1.6.5` working fine.
In `-Version 1.9.4` class library disappears.

Updated csporj. 

![image](https://user-images.githubusercontent.com/10028131/111978300-0c742380-8b04-11eb-81bd-f893d6eea4f2.png)

**Comment by jozefchmelar** [comment]
@kumaraswamygaviyappa  I'm afraid you're still using the old csproj format.  Edit the csproj file (in notepad, vscode, sublime) so it looks like this https://github.com/Inxton/Examples-Inxton.Package.Vortex.Core/blob/master/HansPlcConnector/HansPlcConnector.csproj  . 

Do you use Visual Studio 2019 ?

![image](https://user-images.githubusercontent.com/11136013/111978839-ab991b00-8b04-11eb-8ed0-6ba07eef5278.png)

Or upload zipped project here, or send it to jozef.chmelar@inxton.com so we can take a look at it.

**Comment by kumaraswamygaviyappa** [comment]
@jozefchmelar ,
If you see the image i shared , added `<PackageReference Include="Inxton.Vortex.Compiler.Console" Version="1.9.6" />`

I have updated working project for the [Version="1.6.5"](https://github.com/kumaraswamygaviyappa/InxtonCoreConsole)
