### ISSUE TITLE
Running builder reports 'Vortex Builder does not exist'

### ISSUE THREAD

**Issue by pierk007** [Inxton/Feedback#8]
I cloned a repo from GH, when I try to run Vortex Builder using extension I get following:

![image](https://user-images.githubusercontent.com/33576618/111782088-ea3a9580-88b8-11eb-9a6c-83320ca6a739.png)

**Comment by Inxton-Dev** [comment]
Hi @pierk007,

Your solution folder should contain ```_Vortex\builder\vortex.compiler.console.exe```. If this file does not exist open your solution open and navigate to ```Package Manager Console```. Once the console is opened the compiler should be copied to that folder. You may also need to build your solution.

![image](https://user-images.githubusercontent.com/60608129/111783195-40f49f00-88ba-11eb-8b2d-6d15c9373939.png)
