### ISSUE TITLE
Which variable types are supported as added properties

### ISSUE THREAD

**Issue by JurajSpisiak** [Inxton/Feedback#9]
Using added properies as mentioned [here](https://github.com/Inxton/documentation/blob/master/apis/Inxton.vortex.compiler.console/Conceptual/AddedProperties.md) will generate string or integer variables for hmi. Is it possible to define properties of type BOOL?

**Comment by Inxton-Dev** [comment]
@JurajSpisiak It should possible to define added properties of any primitive type on complex types. The primitive types have only predefined added properties that are declared in the wrapper classes of given primitive type. Let me check the feasibility of the implementation. I will come back to you shortly.

**Comment by Inxton-Dev** [comment]
@JurajSpisiak you are correct, only string and number literals are allowed. I am adding your suggestion in backlog (FXT520) and we will add it some future sprint.
